# Generated by Django 5.2 on 2025-04-12 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardHolderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequent_flyer_number', models.CharField(blank=True, max_length=100)),
                ('ref_title', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_required_tax_invoice', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FraudCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_reference_number', models.CharField(blank=True, max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('provider_response_message', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_code', models.CharField(max_length=100)),
                ('brand_type', models.CharField(blank=True, max_length=50)),
                ('brand_category', models.CharField(blank=True, max_length=50)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('scheme', models.CharField(blank=True, max_length=50)),
                ('last4', models.CharField(blank=True, max_length=4)),
                ('expiry_month', models.CharField(blank=True, max_length=2)),
                ('expiry_year', models.CharField(blank=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='UIComponentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_code', models.CharField(blank=True, max_length=100)),
                ('client_id', models.CharField(blank=True, max_length=100)),
                ('customer_code', models.CharField(max_length=100)),
                ('order_id', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('amount_to_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('required_card_holder_detail', models.BooleanField(default=False)),
                ('transaction_type', models.CharField(blank=True, max_length=50)),
                ('ui_component_string', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CardTokenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=19)),
                ('cvv', models.CharField(max_length=4)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('scheme', models.CharField(blank=True, max_length=50)),
                ('save_for_future', models.BooleanField(default=True)),
                ('customer_code', models.CharField(max_length=100)),
                ('card_holder_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.cardholderdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_init_auth', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant_code', models.CharField(blank=True, max_length=100)),
                ('customer_code', models.CharField(blank=True, max_length=100)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('order_id', models.CharField(blank=True, max_length=255)),
                ('bank_transaction_id', models.CharField(blank=True, max_length=255)),
                ('gateway_response_code', models.CharField(blank=True, max_length=50)),
                ('gateway_response_message', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('fraud_check_type', models.CharField(blank=True, max_length=50)),
                ('fraud_check_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.fraudcheckresult')),
            ],
        ),
        migrations.CreateModel(
            name='TokenisedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_code', models.CharField(blank=True, max_length=100)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.CharField(blank=True, max_length=50)),
                ('bin', models.CharField(blank=True, max_length=6)),
                ('last4', models.CharField(blank=True, max_length=4)),
                ('expiry_month', models.CharField(blank=True, max_length=2)),
                ('expiry_year', models.CharField(blank=True, max_length=4)),
                ('customer_code', models.CharField(blank=True, max_length=100)),
                ('brand_type', models.CharField(blank=True, max_length=50)),
                ('brand_category', models.CharField(blank=True, max_length=50)),
                ('merchant_reference', models.CharField(blank=True, max_length=255)),
                ('save_card_for_future', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('card_holder_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.cardholderdetail')),
                ('card_token_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.cardtokenrequest')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('ui_component_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.uicomponentrequest')),
            ],
        ),
    ]
